import dotenv
import os

dotenv.load_dotenv()

CONCURRENT_MODEL_DIR = os.getenv("CONCURRENT_MODEL_DIR")
CONCURRENT_CONCURRENT_NESTED_MODEL_DIR = os.getenv(
    "CONCURRENT_CONCURRENT_NESTED_MODEL_DIR")
EXCLUSIVE_MODEL_DIR = os.getenv("EXCLUSIVE_MODEL_DIR")
EXCLUSIVE_EXCLUSIVE_NESTED_MODEL_DIR = os.getenv(
    "EXCLUSIVE_EXCLUSIVE_NESTED_MODEL_DIR")
LOOP_MODEL_DIR = os.getenv("LOOP_MODEL_DIR")

CONCURRENT_RESULT_DIR = os.getenv("CONCURRENT_RESULT_DIR")
CONCURRENT_CONCURRENT_NESTED_RESULT_DIR = os.getenv(
    "CONCURRENT_CONCURRENT_NESTED_RESULT_DIR")
EXCLUSIVE_RESULT_DIR = os.getenv("EXCLUSIVE_RESULT_DIR")
EXCLUSIVE_EXCLUSIVE_NESTED_RESULT_DIR = os.getenv(
    "EXCLUSIVE_EXCLUSIVE_NESTED_RESULT_DIR")
LOOP_RESULT_DIR = os.getenv("LOOP_RESULT_DIR")

if __name__ == "__main__":
    pass
